# Generated by Django 5.0 on 2024-09-08 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediamodel',
            old_name='logo',
            new_name='image',
        ),
    ]
